services:
  stats-server:
    build: ./ewm-stat-service/stat-server
    image: java-explore-with-me-stat-srv
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:16.1
    container_name: ewm-stat-db

  ewm-service:
    build: ./ewm-main-service
    image: java-explore-with-me-main-srv
    container_name: ewm-main-server
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:16.1
    container_name: ewm-main-db
